カスタムコントロール編集機能関連の修正・編集
kurusugawa-computer/cumo pull request #142
Opened 2024-08-01 08:04 UTC by NovanMondon

**修正・解決されるissue**
Fix #139 
Fix #140 

**目的**
- #139 のように、これまでは画面上に表示されるGUIについて、自分で追加したカスタムコントロールしか削除することができなかった。そのため、最初からあるrotateSpeedなどのコントロールを消したいという問題が発生した。
  - また、それらのコントロールを消してしまうと、今度はrotateSpeedなどの値を変えることができなくなった。（コントロールを変えることで間接的にプロパティを変えていたため）
- さらに、GUIまわりのプログラム自体にも若干未整理な点が残されていた。

**変更点**
- set_property APIを追加
  - 呼び出し側からプロパティの値を直接変更できる
- すべての既定のコントロールにUUIDを追加
  - すべての既定のコントロールを削除することができる
  - すべての既定のコントロールの値を変更することができる
- GUIにかかわるプログラム構成の変更
  - UUIDのみからコントロールを特定できるようにしたことで、プログラムを整理しつつ、上記の機能追加を行えるようにした

**確認手順**
例えば、GUIのルートを削除する場合、__main__.py内で以下を呼び出す
```
    viewer.remove_custom_control(DefaultUUID.CUSTOM_ROOT)
```
DefaultUUIDクラスには、既定のコントロールのUUIDが登録してある

**備考**

**確認事項**
 - [x] 修正途中であればDraftになっていますか？
 - [x] タイトルはわかりやすいですか？(何をどうするを書いてください)

2024-08-01 08:12 UTC, NovanMondon commented
要求されていた機能はできたと思うので、すり合わせなどのために一旦PRを作成しました。
現状で機能が問題なく達成できているか、確認をお願いします。
イメージと異なるところなども修正したいです。

また、問題なければ、もう少し大きな修正をしたいと考えています。
具体的には
- dat-guiからlil-guiへの更新
- GUI関連の操作をgui_manager.tsにまとめ、handler/以下を簡略化する
- 一旦既存のremove_custom_controlで全GUIを削除できるように作ったが、もっと直感的なGUI操作APIを新しく立てて、そこで全GUIが削除できるようにしたい？要検討
  - UUIDを全既定パーツに指定するというゴリ押しをやめられるならやめたい
  - プロパティ名とコントロール名が常に同一のUUIDであるという設計は非直感的に思えるので、変えた方が良さそうなら変えたい

2024-08-01 08:51 UTC, kotet requested changes
コントロールの整理はいい感じだと思います。Python側のインターフェースはちょっと直してほしいのでコメントしました

2024-08-01 08:51 UTC, kotet commented on lib/cumo/_internal/members/manage_properties.py
> +    """
プロパティのパスはライブラリのユーザには公開されていない内部仕様なので、それを指定させるのは避けたいです。`set_camera_*`メソッドを追加するなどして、できることの選択肢がPython側のドキュメントやインターフェースで表現してください。

2024-08-01 09:00 UTC, kotet commented
> マージ先はmasterで合っていますか？
:+1:

2024-08-05 11:00 UTC, NovanMondon commented
残り
- dat-guiからlil-guiへの更新
- 挙動に不安がある場所の動作チェック

2024-08-06 02:54 UTC, kotet requested changes

2024-08-06 02:54 UTC, kotet commented on lib/cumo/_internal/members/set_config.py
> +def set_use_perspective(
カメラの投影法の切り替えは`set_orthographic_camera`と`set_perspective_camera`があるので機能が重複してしまいます(protobufにおける`server_pb2.SetCamera.CameraMode`に相当)。メソッド名もコントロールのみにとらわれた見方の名前になっちゃってて汎用性に欠けるので、`set_use_perspective`の方を削除してください。

(このレビューをするにあたって改めて`set_orthographic_camera`を見返すと`frustum_height`を指定しないときだけカメラを切り替えるようになってて挙動がわかりにくいですね……後で修正します)

2024-08-06 02:54 UTC, kotet commented on client/src/websocket/handler/set_config.ts
> +      break;
たしかプロパティを直接変えた時に`dat.gui`の`onChange`イベントが発行されるような仕組みは無かったはずなので、これだとカメラの移動速度は変化しないと思います。`onChange`内で行っている操作をここでも行って、変更をカメラに反映させてください。これ以降の他の設定項目も同様です

2024-08-06 04:27 UTC, NovanMondon commented on client/src/websocket/handler/set_config.ts
> +      break;
それでしたら、viewer.config.controlsを廃止してcameraInputの内容を直接操作するのはどうでしょうか。
GUIもcameraInputに紐づければ問題ないと思います。

2024-08-06 04:39 UTC, NovanMondon commented on client/src/gui/gui_manager.ts
> +    // const labels = document.querySelectorAll<HTMLDivElement>('.dg .property-name').values();
ここ、lil-guiでwidthを指定する方法が分からなかったので一旦コメントアウトしました。

質問ですが、もともとこの関数はlil-guiの横幅を制限する機能、ということで合っていますか？
そういう用途だと私はcssを使うのをイメージするのですが、スクリプトでやっていた理由は何でしょうか？

2024-08-06 04:45 UTC, kotet commented on client/src/websocket/handler/set_config.ts
> +      break;
確かにそれで良いかもしれないです。やってみて動作確認ができたら大丈夫です

2024-08-06 04:50 UTC, kotet commented on client/src/gui/gui_manager.ts
> +    // const labels = document.querySelectorAll<HTMLDivElement>('.dg .property-name').values();
検討はしたはずで、dat.guiにwidthプロパティが用意されているのでその枠組みに乗っかったということだと思います。lil-guiで適した方法が変化したならそちらを採用しても構いません。

2024-08-06 10:00 UTC, kotet commented on client/src/gui/gui_manager.ts
> +    // const labels = document.querySelectorAll<HTMLDivElement>('.dg .property-name').values();
このコードが入る元となったIssue: #15
Issue見返して思い出したんですが「自動で幅を調整して、なおかつ手動で縮めたり伸ばしたりされた時はそちらを尊重する」という挙動を実現したくてスクリプトを使ったという記憶が蘇ってきました。この「手動でも幅を変えられる」という挙動はその方が良いかなと @kotet が考えて入れたもので、明示的にユーザが求めたものではないので必ずしも維持する必要はないです

2024-08-06 22:47 UTC, NovanMondon commented
GUIの幅調整について、sassで修正してみました。
一応動作確認はしましたが、関連イシューの問題が再発していないか、お手数ですが確認していただきたいです。

2024-08-06 22:50 UTC, NovanMondon commented
vite.config.tsですが、いつからか仕様が変わり、devcontainer内で起動したviteサーバーをローカルからアクセスするためにhostを設定する必要が発生したと思います。
ですので、vite.config.tsのserver.hostを設定する必要があると思いますが、大丈夫ですか？
https://zenn.dev/frog/articles/5e26e454309d81
https://ja.vitejs.dev/config/server-options.html#server-host

2024-08-08 02:23 UTC, kotet commented
>  ですので、vite.config.tsのserver.hostを設定する必要があると思いますが、大丈夫ですか？
あんまり大丈夫じゃないので修正お願いします

2024-08-08 02:26 UTC, kotet requested changes
14文字以上のテキストを入れた時に全文を読む方法が存在しないようです。修正お願いします。
![image](https://github.com/user-attachments/assets/bebad0c7-6a19-480a-98fd-f7a8ee9e093a)

2024-08-19 02:16 UTC, kotet requested changes
手動調節ができるようになったので、あとはドキュメントを書いてくれれば最低限完成でいいと思います。幅の自動調節がうまく動いていないようですが、解決は難しそうですか?

```
viewer.add_custom_button(
    name="1234567890123456789012345678901234567890", on_changed=lambda dummy: print("test")
)
```

![image](https://github.com/user-attachments/assets/51ebc89f-4614-4b63-a807-f32d288f21c5)

2024-08-19 02:16 UTC, kotet commented on lib/cumo/_internal/members/set_config.py
> +) -> None:
`camera.py`を参考にドキュメントを書いてください

2024-08-21 04:21 UTC, NovanMondon commented
CSSでの解決を目指したのですが、レイアウトの仕様が複雑でなかなか想定通りには動かないようです。
スクリプト側で調整する仕様に戻します。

2024-08-27 08:44 UTC, kotet approved these changes
動作確認できました! #140 も含めて解決してるっぽいですね

2024-10-16 08:42 UTC, yama-is-bocchi commented
質問です。
READMEの通りに環境を構築できたのですが、pcdを読み込むところでエラーが発生してしまいます。
色々なデータセットで試してみたのですが、上手くできないです。
テストデータは何を使用していますか?

↓出力されるエラーコードです
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspaces/cumo/lib/cumo/__main__.py", line 124, in <module>
    main()
  File "/workspaces/cumo/lib/cumo/__main__.py", line 27, in main
    radius = send_pointcloud_pcd(viewer, args.pcd_filepath)
  File "/workspaces/cumo/lib/cumo/__main__.py", line 73, in send_pointcloud_pcd
    viewer.send_pointcloud_pcd(b)
  File "/workspaces/cumo/lib/cumo/_internal/members/send_object.py", line 67, in send_pointcloud_pcd
    rgb_u32: numpy.ndarray = pc_data["rgb"]
ValueError: no field of name rgb
```

2024-10-17 03:41 UTC, NovanMondon commented
テストデータはpointcloudライブラリのpcl_logo.pcdをダウンロードして実行しています
https://github.com/PointCloudLibrary/pcl/blob/master/test/pcl_logo.pcd

2024-10-17 07:16 UTC, kotet commented
> 提案ですが、初見で触る人視点だとこのファイルに辿り着くのが困難だと思うので、READMEのcumo開発者向けに追記するのはどうでしょうか?

実はこのPRが作られたあとに開発環境の更新があり、`master`ブランチでは`make lib/sample_data.pcd`でテスト用データが落ちてくるようになっています。そういうわけなので一旦は自力でサンプルデータを用意するか、またはリベースしてこのPRを更新するという手もあります

2024-10-18 00:25 UTC, yama-is-bocchi commented
> > 提案ですが、初見で触る人視点だとこのファイルに辿り着くのが困難だと思うので、READMEのcumo開発者向けに追記するのはどうでしょうか?
> 
> 実はこのPRが作られたあとに開発環境の更新があり、`master`ブランチでは`make lib/sample_data.pcd`でテスト用データが落ちてくるようになっています。そういうわけなので一旦は自力でサンプルデータを用意するか、またはリベースしてこのPRを更新するという手もあります

なるほど、了解しました。
であれば大丈夫ですね!

2024-10-18 00:26 UTC, yama-is-bocchi approved these changes
Issueの解決、動作確認しました。

2024-10-18 02:45 UTC, merged